General content of the page
JbirdL86/Youtube-Project pull request #4
Opened 2020-06-23 22:11 UTC by JbirdL86

By mistake user-column branch was merged to the master before making this pull request.

2020-06-24 00:14 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-24 00:39 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @JbirdL86 @Huemac-Alfredo** 
Good job with your first submission for this project :muscle:  
Your HTML pass the validations :clap: :clap: :clap:  
There are some issues to solve before you can go ahead:
- [ ] for your next "review request" please provide a more meaningful description
- [ ] Your live demo is not working, you can use  https://raw.githack.com/ to create a live demo for this project.
- [ ] Don't use important
- [ ] Don't overuse ID Selectors
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-24 00:39 UTC, andresporras3423 commented on style.css
> -	#menucont{
Don't overuse ID selectors

2020-06-24 00:39 UTC, andresporras3423 commented on style.css
> -		color: #d1cccc !important;
Don't use !important

2020-06-24 00:39 UTC, andresporras3423 commented on style.css
> -	}
This selector and selector on line 120 both have the same style definition. Don't repeat yourself, group selectors.

2020-06-24 14:37 UTC, JbirdL86 commented on style.css
> -	}
Done

2020-06-24 14:37 UTC, JbirdL86 commented on style.css
> -		color: #d1cccc !important;
Done

2020-06-24 14:38 UTC, JbirdL86 commented on style.css
> -	#menucont{
I'm not sure how to solve this

2020-06-25 15:55 UTC, JbirdL86 commented
@andresporras3423 I'm not sure if this pull request needs to stay or we need to create a new one?

2020-06-26 23:56 UTC, elmejdki commented
# Hi, @andresporras3423 create a new pull request and remember to never close a pull request that was not approved.
## Happy Coding :tophat:

2020-06-26 23:59 UTC, elmejdki commented
# @andresporras3423 Actually, I think you need to create a new repository please contact me on slack so I can explain to you the process. you will find me as _Zakariae El Mejdki_.

2020-07-02 19:14 UTC, closed without merging